version: "3"

services:
  php:
    build: .docker/php
    container_name: "movie-api-container"
    image: server-apache
    env_file:
      - .env
    volumes:
      - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www/html
    ports:
      - 8000:80
    restart: always
